import Nav from "@/components/Nav";
import Provider from "@/components/Provider";
import "@/styles/main.css";

import { Bricolage_Grotesque } from "next/font/google";

const bricolage_grotesque = Bricolage_Grotesque({ subsets: ["latin"] });

export const metadata = {
  title: "My Next Trip",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${bricolage_grotesque.className} bg-gradient-to-tr from-slate-200 to-slate-100 bg-no-repeat min-h-screen`}
      >
        <Provider>
          <Nav />

          <main>{children}</main>
        </Provider>
      </body>
    </html>
  );
}
